// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Bar struct {
	Time   int32   `json:"time"`
	Close  float64 `json:"close"`
	High   float64 `json:"high"`
	Low    float64 `json:"low"`
	Open   float64 `json:"open"`
	Volume float64 `json:"volume"`
}

type LibrarySymbolInfo struct {
	Name                 string   `json:"name"`
	FullName             string   `json:"fullName"`
	Description          string   `json:"description"`
	Type                 string   `json:"type"`
	Session              string   `json:"session"`
	Timezone             string   `json:"timezone"`
	Exchange             string   `json:"exchange"`
	Minmov               int32    `json:"minmov"`
	Pricescale           int32    `json:"pricescale"`
	HasIntraday          bool     `json:"has_intraday"`
	VisiblePlotsSet      string   `json:"visible_plots_set"`
	HasWeeklyAndMonthly  bool     `json:"has_weekly_and_monthly"`
	SupportedResolutions []string `json:"supported_resolutions"`
	VolumePrecision      int32    `json:"volume_precision"`
	DataStatus           string   `json:"data_status"`
}

type Query struct {
}

type Symbol struct {
	Description string `json:"description"`
	Exchange    string `json:"exchange"`
	Symbol      string `json:"symbol"`
	Ticker      string `json:"ticker"`
	Type        string `json:"type"`
}
