name: Conventional Commits

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Conventional Commits
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: webiny/action-conventional-commits@v1.3.0
        with:
          allowed-commit-types: "build,chore,ci,docs,feat,fix,perf,refactor,revert,style,test" 

